# Main docker-compose configuration for krovli38 project
# Includes frontend, admin panel, backend server, MongoDB, and Nginx reverse proxy

version: '3.8'

services:
  frontend:
    image: gimmyhat/krovli38-frontend:latest
    restart: always
    networks:
      - app-network

  admin:
    image: gimmyhat/krovli38-admin:latest
    restart: always
    networks:
      - app-network

  server:
    image: gimmyhat/krovli38-server:latest
    restart: always
    environment:
      - MONGODB_URI=mongodb://admin:admin_password@mongodb:27017/krovli38?authSource=admin
      - NODE_ENV=production
      - JWT_SECRET=your_super_secret_key_for_jwt_tokens_krovli38
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=krovli38
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - frontend
      - admin
      - server

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 