version: '3.8'

# Оверлей для локальной разработки
services:
  mongodb:
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_local:/data/db

  server:
    build:
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ../server/src:/app/src
      - ../server/package.json:/app/package.json
      - ../server/tsconfig.json:/app/tsconfig.json

  frontend:
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../package.json:/app/package.json
      - ../vite.config.ts:/app/vite.config.ts

  admin:
    volumes:
      - ../admin-panel/src:/app/src
      - ../admin-panel/public:/app/public
      - ../admin-panel/package.json:/app/package.json
      - ../admin-panel/vite.config.ts:/app/vite.config.ts

  nginx:
    ports:
      - '80:80'

volumes:
  mongodb_data_local: 