version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=krovli38
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev: 