version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: krovli38-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    restart: unless-stopped

volumes:
  mongodb_data: 