name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: gimmyhat
  FRONTEND_IMAGE: gimmyhat/krovli38-frontend
  ADMIN_IMAGE: gimmyhat/krovli38-admin
  SERVER_IMAGE: gimmyhat/krovli38-server
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_DB: krovli38
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  CLOUDINARY_UPLOAD_PRESET: ${{ secrets.CLOUDINARY_UPLOAD_PRESET }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/frontend/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache,mode=max

      - name: Build and push admin panel
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/admin/Dockerfile
          push: true
          tags: ${{ env.ADMIN_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.ADMIN_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.ADMIN_IMAGE }}:buildcache,mode=max

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/server/Dockerfile
          push: true
          tags: ${{ env.SERVER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.SERVER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.SERVER_IMAGE }}:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker/docker-compose.yml,docker/nginx/,server/src/scripts/"
          target: "/root/krovli38"
          strip_components: 1

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DOCKER_HUB_USERNAME,MONGO_USER,MONGO_PASSWORD,JWT_SECRET,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,CLOUDINARY_UPLOAD_PRESET,MONGO_DB
          script: |
            cd /root/krovli38
            
            # Создаем файл .env с переменными окружения
            echo "DOCKER_REGISTRY=${DOCKER_HUB_USERNAME}" > .env
            echo "MONGO_USER=${MONGO_USER:-admin}" >> .env
            echo "MONGO_PASSWORD=${MONGO_PASSWORD:-admin_password}" >> .env
            echo "JWT_SECRET=${JWT_SECRET:-default_jwt_secret}" >> .env
            echo "CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}" >> .env
            echo "CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}" >> .env
            echo "CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}" >> .env
            echo "CLOUDINARY_UPLOAD_PRESET=${CLOUDINARY_UPLOAD_PRESET}" >> .env
            
            # Создаем директорию для бэкапов если её нет
            mkdir -p db_backups
            
            # Создаем бэкап базы данных перед обновлением (если MongoDB запущена)
            if docker ps | grep -q mongodb; then
              echo "Creating database backup..."
              BACKUP_NAME="backup_$(date +%Y%m%d_%H%M%S).gz"
              docker compose exec -T mongodb mongodump --uri="mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-admin_password}@localhost:27017/${MONGO_DB}?authSource=admin" --archive --gzip > "db_backups/$BACKUP_NAME" || echo "Backup failed but continuing..."
            fi
            
            # Останавливаем старые контейнеры
            echo "Stopping old containers..."
            docker compose down
                        
            # Подтягиваем новые образы
            echo "Pulling new images..."
            docker compose pull
            
            # Запускаем контейнеры
            echo "Starting new containers..."
            docker compose up -d
            
            # Ждем, пока MongoDB будет готова
            echo "Waiting for MongoDB to be ready..."
            sleep 20
            
            # Проверяем и инициализируем админа
            echo "Checking admin user..."
            docker compose exec -T server node dist/scripts/checkAdmin.js || docker compose exec -T server node dist/scripts/createAdmin.js
            
            # Проверяем здоровье сервисов
            echo "Checking services health..."
            for i in {1..30}; do
              if curl -s http://localhost/api > /dev/null; then
                echo "API is responding"
                break
              fi
              if [ $i -eq 30 ]; then
                echo "API failed to respond"
                # Восстанавливаем из бэкапа в случае проблем
                docker compose down
                docker compose up -d mongodb
                sleep 10
                if [ -f "db_backups/$BACKUP_NAME" ]; then
                  echo "Restoring from backup..."
                  docker exec -i mongodb mongorestore --uri="mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-admin_password}@localhost:27017/${MONGO_DB}?authSource=admin" --archive --gzip < "db_backups/$BACKUP_NAME" || echo "Restore failed"
                fi
                docker compose up -d
                exit 1
              fi
              echo "Waiting for API... ($i/30)"
              sleep 2
            done
            
            # Очистка старых образов
            docker system prune -f
            
            # Удаляем старые бэкапы (оставляем последние 5)
            cd db_backups && ls -t | tail -n +6 | xargs -r rm -- 